// Mock data for posts
export const posts = [
    {
        id: "1",
        title: "The Art of Component Composition",
        excerpt: "How to build maintainable UI components that scale with your application",
        date: "2023-05-15",
        layer: "frontend",
        tags: ["react", "architecture", "patterns"],
        slug: "component-composition",
        author: "John Doe",
        readTime: "5 min read",
        debug_notes: [],
    },
    {
        id: "2",
        title: "API Design Principles for Backend Engineers",
        excerpt: "Creating intuitive, consistent, and evolvable APIs that developers love",
        date: "2023-06-22",
        layer: "backend",
        tags: ["api", "rest", "graphql"],
        slug: "api-design-principles",
        author: "Jane Smith",
        readTime: "8 min read",
        debug_notes: [],
    },
    {
        id: "3",
        title: "Infrastructure as Code: Beyond the Basics",
        excerpt: "Advanced patterns for managing cloud infrastructure with code",
        date: "2023-07-10",
        layer: "devops",
        tags: ["terraform", "aws", "iac"],
        slug: "infrastructure-as-code",
        author: "Peter Jones",
        readTime: "12 min read",
        debug_notes: [],
    },
    {
        id: "4",
        title: "System Design: Scaling to Your First Million Users",
        excerpt: "Architectural patterns and considerations for high-scale applications",
        date: "2023-08-05",
        layer: "architecture",
        tags: ["scaling", "distributed-systems", "performance"],
        slug: "scaling-to-million-users",
        author: "Mary Johnson",
        readTime: "15 min read",
        debug_notes: [],
    },
    {
        id: "5",
        title: "Building Engineering Teams That Last",
        excerpt: "Strategies for creating a culture of growth, trust, and technical excellence",
        date: "2023-09-18",
        layer: "peopleware",
        tags: ["leadership", "culture", "mentorship"],
        slug: "building-engineering-teams",
        author: "David Williams",
        readTime: "10 min read",
        debug_notes: [],
    },
    {
        id: "6",
        title: "Late Night Debugging: Tales from Production",
        excerpt: "War stories and lessons learned from critical production incidents",
        date: "2023-10-30",
        layer: "overflow",
        tags: ["debugging", "incidents", "lessons"],
        slug: "late-night-debugging",
        author: "Susan Brown",
        readTime: "7 min read",
        debug_notes: [],
    },
]
